sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-23
    - android-25
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: lint
      language: node_js
      os: linux
      node_js: "6"
      script: 
        - cd bin/dist && cat README.md | grep -q "# Installation" && cd ../..
        - cd bin/dist && cat README.md | grep -q "# Configuration" && cd ../..
        - cd bin/dist && cat README.md | grep -q "# API" && cd ../..
        - cd bin/dist && cat README.md | grep -q "# Usage" && cd ../..
        - cd bin/dist && cat package.json | grep -q "\"license\"" && cd ../..
        - cd bin/dist && cat package.json | grep -q "\"nativescript\"" && cd ../..
        - grunt exec:tslint

    - stage: build
      language: android
      os: linux
      env: 
        - Android="25"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: 
        - cd demo && npm install && tns build android && cd ..
        - cd demo-ng && npm install && tns build android && cd ..

    - stage: build
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: 
        - cd demo && npm install && tns build ios && cd ..
        - cd demo-ng && npm install && tns build ios && cd ..

    - stage: webpack
      language: android
      os: linux
      env:
        - Android="25"
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: 
        - cd demo && npm install && npm run ns-bundle --android --build-app --uglify && cd ..
        - cd demo-ng && npm install && npm run ns-bundle --android --build-app --uglify && cd ..
    
    - stage: webpack
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
        - Platform="iOS"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: 
        - cd demo && npm install && npm run ns-bundle --ios --build-app --uglify && cd ..
        - cd demo-ng && npm install && npm run ns-bundle --ios --build-app --uglify && cd ..

before_deploy:
    - cd bin/dist

deploy:
    language: node_js 
    node_js: "6"
    provider: npm
    email: "peter@tangrasoft.com"
    api_key:
        secure: U3FCudZUlh/TjfF51/binIIWkwKsbuMB1OivJrJ4HWLlxNcbes91uBVFLJ5aktg+yJxR72yH/cJ7BQRh/I18AUX+tnLcUHR9bz31WdM7+njm5gmAbb2c4cypKZ1L1yeIhhOtL7wZqYzvP5Jbthuv/ewQkYtMJXZiOXuYFhOtMUXMVAS8PIQfNbCCW7UFqhGAolfSHExVv4OgJh/GAAcscg8XPdArUOicZhGSSSRc5J71S8R9z46g02BXMx0DHMgcM0gTzkDjq0yA3ns+XCqEQrJNQC8jvD8OPY49VG+rKBY/xGO6JzRTue5HlmsXNbI98bk+qljaXCFllv3RBW6mu5lFBhDDJtzSrr3PuyddOC1EnCStDP1tfvj6tPTw7mMWY3LfOBzPl9E8T1HxJBbmGEpjVLvmBlujhw8osbnLYJjgK+qETjvBn3mem6NhGd4H/q3Q1iioVwRWwrVCeVFrpoq/Aa2ySZYKGU4wqJDYbGIOgBr8PB3pFc4BauEJhQmhoP8vF4s6yNEfTkXuA61Nsqwv2DuG1uqTcmcrSeXRTaA2nWok8oEqQ/QAk/t9HFDuZLQhCgDJaXoKmDtNsVQ/rfTyMNBTXm95IWwSlQb2RwYxsgagKEBk86myYkzh1tQJdERIWqF2zmohQTMaiwqv+ssDW1eyydPcnkFfyQyAPn8=
    skip_cleanup: true
    on:
        branch: release