android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: grunt exec:tslint

    - stage: "WebPack"
      os: osx
      env:
        - Platform="iOS"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: cd demo && npm install && npm run ns-bundle --ios --build-app --uglify && cd ../demo-ng && npm install && npm run ns-bundle --ios --build-app --uglify
    - language: android
      os: linux
      env:
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: cd demo && npm install && npm run ns-bundle --android --build-app --uglify && cd ../demo-ng && npm install && npm run ns-bundle --android --build-app --uglify