sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - android-23
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: 
        - cd bin/dist && cat README.md | grep -q "# Installation" && cd ../..
        - cd bin/dist && cat README.md | grep -q "# Configuration" && cd ../..
        - cd bin/dist && cat README.md | grep -q "# API" && cd ../..
        - cd bin/dist && cat README.md | grep -q "# Usage" && cd ../..
        - cd bin/dist && cat package.json | grep -q "\"license\"" && cd ../..
        - cd bin/dist && cat package.json | grep -q "\"nativescript\"" && cd ../..
        - grunt exec:tslint

    - stage: "Build"
      language: android
      os: linux
      env: 
        - Android="25"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: 
        - cd demo && npm install && tns build android && cd ..
        - cd demo-ng && npm install && tns build android && cd ..
    - os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: 
        - cd demo && npm install && tns build ios && cd ..
        - cd demo-ng && npm install && tns build ios && cd ..

    - stage: "WebPack"
      language: android
      os: linux
      env:
        - Android="25"
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: 
        - cd demo && npm install && npm run ns-bundle --android --build-app --uglify && cd ..
        - cd demo-ng && npm install && npm run ns-bundle --android --build-app --uglify && cd ..
    - os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
        - Platform="iOS"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: 
        - cd demo && npm install && npm run ns-bundle --ios --build-app --uglify && cd ..
        - cd demo-ng && npm install && npm run ns-bundle --ios --build-app --uglify && cd ..
